import React from "react"
import ReactDOM from "react-dom/client"
import Header from "./components/Header"
import Body from "./components/Body"
import Footer from "./components/Footer"


const data = [
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "720566",
        name: "Farki Lassi",
        uuid: "d949525f-6c1f-4bea-9ec6-84d16ca7c00d",
        city: "10",
        area: "Bapunagar",
        totalRatingsString: "Too Few Ratings",
        cloudinaryImageId: "391f616f1be43d555dd59ef8050a2d4d",
        cuisines: ["Beverages", "Desserts", "Sweets"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 42,
        minDeliveryTime: 42,
        maxDeliveryTime: 42,
        slaString: "42 MINS",
        lastMileTravel: 0.8999999761581421,
        slugs: {
          restaurant: "farki-lassi-bapunagar-bapunagar",
          city: "ahmedabad",
        },
        cityState: "10",
        address:
          "GF-11,12,SUNRISE CHEMBER,INDIA COLONY ROAD,THAKKARBAPANAGAR,BAPUNAGAR,AHMEDABAD-380024",
        locality: "Sunrise Chember",
        parentId: 429366,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 2800,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2800,
          message: "",
          title: "Delivery Charge",
          amount: "2800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "HEAVY",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "0.8 kms",
        hasSurge: false,
        sla: {
          restaurantId: "720566",
          deliveryTime: 42,
          minDeliveryTime: 42,
          maxDeliveryTime: 42,
          lastMileTravel: 0.8999999761581421,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "HEAVY",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "--",
        totalRatings: 0,
        new: true,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "94352",
        name: "Big Bite Fast Food",
        uuid: "fd696309-591c-4f1b-855f-f7a12cb6ea1d",
        city: "10",
        area: "Nikol",
        totalRatingsString: "5000+ ratings",
        cloudinaryImageId: "jq6dev5md1lrtmrzsrdj",
        cuisines: ["Pizzas", "Fast Food", "Beverages", "Burgers", "Snacks"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 49,
        minDeliveryTime: 49,
        maxDeliveryTime: 49,
        slaString: "49 MINS",
        lastMileTravel: 3,
        slugs: {
          restaurant: "big-bite-fast-food-nikol-bapunagar",
          city: "ahmedabad",
        },
        cityState: "10",
        address:
          "26, Murtidham Complex, Opposite Gayatri Gathiya, Raspan Char Rasta, D - Mart Road, New India Colony, New Nikol, Nikol, Ahmedabad",
        locality: "Nikol",
        parentId: 45494,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "FLAT150 off",
          shortDescriptionList: [
            {
              meta: "FLAT150 off | Use STEALDEAL150",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FLAT150 off | Use STEALDEAL150",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "₹150 OFF",
          shortDescriptionList: [
            {
              meta: "Use STEALDEAL150",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FLAT150 off | Use STEALDEAL150",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3300,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3300,
          message: "",
          title: "Delivery Charge",
          amount: "3300",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "HEAVY",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7205170~p=19~eid=00000189-062b-13b5-1c9e-bab200021369~srvts=1688025633717",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3 kms",
        hasSurge: false,
        sla: {
          restaurantId: "94352",
          deliveryTime: 49,
          minDeliveryTime: 49,
          maxDeliveryTime: 49,
          lastMileTravel: 3,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "HEAVY",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.3",
        totalRatings: 5000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "695770",
        name: "Farki",
        uuid: "4a26b9e8-e5ba-4977-9c55-9164451dc48e",
        city: "10",
        area: "Bapunagar",
        totalRatingsString: "20+ ratings",
        cloudinaryImageId: "e40e9fc6162274b3e8ab2f4a36459332",
        cuisines: ["Beverages", "Ice Cream", "Desserts"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 47,
        minDeliveryTime: 47,
        maxDeliveryTime: 47,
        slaString: "47 MINS",
        lastMileTravel: 1.7000000476837158,
        slugs: {
          restaurant: "farki-bapunagar-bapunagar-5",
          city: "ahmedabad",
        },
        cityState: "10",
        address:
          "29, G.F. 154, 21/1, Sukh Sagar Complex L.B. Marg, R. Tex Compound Oop. Dinesh - Chambers L.B. Shastri R Road Bapunagar Ahmedabad-380024",
        locality: "Sukh Sagar Complex",
        parentId: 78607,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [
          {
            tradeCampaignHeaders: [],
            avgRating: "4.2",
            totalRatings: 50,
            area: "Bapunagar",
            city: "10",
            locality: "Naroda",
            deliveryTime: 40,
            minDeliveryTime: 40,
            maxDeliveryTime: 40,
            slaString: "40 MINS",
            select: false,
            id: "486854",
            slugs: {
              restaurant: "farki-bapunagar-bapunagar-3",
              city: "ahmedabad",
            },
            feeDetails: {
              restaurant_id: 486854,
              fees: [
                {
                  name: "rain",
                  fee: 0,
                  message: "",
                },
                {
                  name: "distance",
                  fee: 2800,
                  message: "",
                },
                {
                  name: "time",
                  fee: 0,
                  message: "",
                },
              ],
              total_fee: 2800,
              message: "",
              title: "Delivery Charge",
              amount: "2800",
              icon: "",
            },
            promoted: false,
            adTrackingID: "",
            aggregatedDiscountInfo: {
              header: "FLAT100 off",
              shortDescriptionList: [
                {
                  meta: "FLAT100 off | Use FLATDEAL",
                  discountType: "Flat",
                  operationType: "RESTAURANT",
                },
              ],
              descriptionList: [
                {
                  meta: "FLAT100 off | Use FLATDEAL",
                  discountType: "Flat",
                  operationType: "RESTAURANT",
                },
              ],
              subHeader: "",
              headerType: 0,
              superFreedel: "",
            },
          },
        ],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 2800,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2800,
          message: "",
          title: "Delivery Charge",
          amount: "2800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "HEAVY",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.7 kms",
        hasSurge: false,
        sla: {
          restaurantId: "695770",
          deliveryTime: 47,
          minDeliveryTime: 47,
          maxDeliveryTime: 47,
          lastMileTravel: 1.7000000476837158,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "HEAVY",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.3",
        totalRatings: 20,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "262978",
        name: "Faasos - Wraps & Rolls",
        uuid: "d3aa1801-71dc-4740-9084-2a74c323a624",
        city: "10",
        area: "Nava Naroda",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "af33b81798b11deba338e94b7585d348",
        cuisines: [
          "Kebabs",
          "Fast Food",
          "Snacks",
          "North Indian",
          "American",
          "Healthy Food",
          "Desserts",
          "Beverages",
        ],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 51,
        minDeliveryTime: 51,
        maxDeliveryTime: 51,
        slaString: "51 MINS",
        lastMileTravel: 2.200000047683716,
        slugs: {
          restaurant: "faasos-bapu-nagar-bapunagar",
          city: "ahmedabad",
        },
        cityState: "10",
        address:
          "SHOP NO 162 TO 164, FIRST FLOOR, MARUTI PLAZA, SARDAR CHOWK, OPP VIJAY PARK SOCIETY, KRISHNANAGAR, AHMEDABAD, GUJARAT 382345",
        locality: "Bapu nagar",
        parentId: 21809,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "FLAT125 off",
          shortDescriptionList: [
            {
              meta: "FLAT125 off | Use FLATDEAL",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FLAT125 off | Use FLATDEAL",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "₹125 OFF",
          shortDescriptionList: [
            {
              meta: "Use FLATDEAL",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FLAT125 off | Use FLATDEAL",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 2800,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2800,
          message: "",
          title: "Delivery Charge",
          amount: "2800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "HEAVY",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2.2 kms",
        hasSurge: false,
        sla: {
          restaurantId: "262978",
          deliveryTime: 51,
          minDeliveryTime: 51,
          maxDeliveryTime: 51,
          lastMileTravel: 2.200000047683716,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "HEAVY",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.2",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "399974",
        name: "Swasthya Juice And Shake Center",
        uuid: "9fbfd7f8-d607-446a-8318-e4bdee022109",
        city: "10",
        area: "Bapunagar",
        totalRatingsString: "100+ ratings",
        cloudinaryImageId: "mhsj1mkktlgyivqughzf",
        cuisines: ["Beverages", "Juices"],
        tags: [],
        costForTwo: 22000,
        costForTwoString: "₹220 FOR TWO",
        deliveryTime: 42,
        minDeliveryTime: 42,
        maxDeliveryTime: 42,
        slaString: "42 MINS",
        lastMileTravel: 1.7999999523162842,
        slugs: {
          restaurant: "swasthya-juice-and-shake-center-bapunagar-bapunagar",
          city: "ahmedabad",
        },
        cityState: "10",
        address: "G-24, Thakkarbapanagar, Ahmedabad, Gujarat 380038, India",
        locality: "Thakkarbapannagar",
        parentId: 256602,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "20% off",
          shortDescriptionList: [
            {
              meta: "20% off | Use JUMBO",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "20% off up to ₹100 on orders above ₹479 | Use code JUMBO",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "20% OFF",
          shortDescriptionList: [
            {
              meta: "Use JUMBO",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "20% off up to ₹100 on orders above ₹479 | Use code JUMBO",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 2800,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2800,
          message: "",
          title: "Delivery Charge",
          amount: "2800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "HEAVY",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7093249~p=22~eid=00000189-062b-13b5-1c9e-bab30002165a~srvts=1688025633717",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.7 kms",
        hasSurge: false,
        sla: {
          restaurantId: "399974",
          deliveryTime: 42,
          minDeliveryTime: 42,
          maxDeliveryTime: 42,
          lastMileTravel: 1.7999999523162842,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "HEAVY",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.5",
        totalRatings: 100,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "139687",
        name: "Fresh Fruit Juice & Platter",
        uuid: "258d850e-b093-490c-8c97-a42c421f681b",
        city: "10",
        area: "Khodiar Nagar",
        totalRatingsString: "500+ ratings",
        cloudinaryImageId: "t8pnt5dgvklyrhtnyoz6",
        cuisines: ["Beverages", "Healthy Food"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 56,
        minDeliveryTime: 56,
        maxDeliveryTime: 56,
        slaString: "56 MINS",
        lastMileTravel: 0.8999999761581421,
        slugs: {
          restaurant: "fresh-fruit-juice-platter-bapunagar-bapunagar",
          city: "ahmedabad",
        },
        cityState: "10",
        address:
          "3 Ravi raj apartment, rata park 2, 80 Ft road, uttamnagar, bapu Nagar",
        locality: "Uttamnagar",
        parentId: 83692,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "FLAT100 off",
          shortDescriptionList: [
            {
              meta: "FLAT100 off | Use FLATDEAL",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FLAT100 off | Use FLATDEAL",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "₹100 OFF",
          shortDescriptionList: [
            {
              meta: "Use FLATDEAL",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FLAT100 off | Use FLATDEAL",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 2800,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2800,
          message: "",
          title: "Delivery Charge",
          amount: "2800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "HEAVY",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "0.8 kms",
        hasSurge: false,
        sla: {
          restaurantId: "139687",
          deliveryTime: 56,
          minDeliveryTime: 56,
          maxDeliveryTime: 56,
          lastMileTravel: 0.8999999761581421,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "HEAVY",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.3",
        totalRatings: 500,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "546166",
        name: "The Lio' Pizza",
        uuid: "fa3bb2d9-d3aa-4799-be06-00a1ab005066",
        city: "10",
        area: "Bapunagar",
        totalRatingsString: "50+ ratings",
        cloudinaryImageId: "o07ij3vcgbytcobt8051",
        cuisines: ["Pizzas", "Italian-American", "Beverages", "Snacks"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 56,
        minDeliveryTime: 56,
        maxDeliveryTime: 56,
        slaString: "56 MINS",
        lastMileTravel: 1.7000000476837158,
        slugs: {
          restaurant: "the-lio'-pizza-bapunagar-bapunagar",
          city: "ahmedabad",
        },
        cityState: "10",
        address:
          "18-19 Shaktidhara Society Opp Indecab Lab Near Bapunagar Toll Naka Thakkarbapanagar , Naroda(North Zone) , Ahmedabad Municipal Corporation, Ahmedabad, Gujarat-382350",
        locality: "Opp Indecab Lab",
        parentId: 236933,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "FLAT150 off",
          shortDescriptionList: [
            {
              meta: "FLAT150 off | Use FLATDEAL",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FLAT150 off | Use FLATDEAL",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "₹150 OFF",
          shortDescriptionList: [
            {
              meta: "Use FLATDEAL",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FLAT150 off | Use FLATDEAL",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 2800,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2800,
          message: "",
          title: "Delivery Charge",
          amount: "2800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "HEAVY",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.7 kms",
        hasSurge: false,
        sla: {
          restaurantId: "546166",
          deliveryTime: 56,
          minDeliveryTime: 56,
          maxDeliveryTime: 56,
          lastMileTravel: 1.7000000476837158,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "HEAVY",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.0",
        totalRatings: 50,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "91493",
        name: "Sam's Pizza",
        uuid: "87bc266f-5e54-44ed-b9ef-de27fd92de58",
        city: "10",
        area: "Bapunagar",
        totalRatingsString: "5000+ ratings",
        cloudinaryImageId: "iiplisybwectzldifrkf",
        cuisines: ["Italian"],
        tags: [],
        costForTwo: 60000,
        costForTwoString: "₹600 FOR TWO",
        deliveryTime: 52,
        minDeliveryTime: 52,
        maxDeliveryTime: 52,
        slaString: "52 MINS",
        lastMileTravel: 1.7000000476837158,
        slugs: {
          restaurant: "sams-pizza-bapunagar-sundarban",
          city: "ahmedabad",
        },
        cityState: "10",
        address:
          "A 35, 1st Floor, Shakti Dhara Society, Opposite Sukh Sagar Complex, Toll Naka, Bapunagar, Ahmedabad",
        locality: " Sukh Sagar Complex",
        parentId: 1358,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "FLAT100 off",
          shortDescriptionList: [
            {
              meta: "FLAT100 off | Use FLATDEAL",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FLAT100 off | Use FLATDEAL",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "₹100 OFF",
          shortDescriptionList: [
            {
              meta: "Use FLATDEAL",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FLAT100 off | Use FLATDEAL",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 2800,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2800,
          message: "",
          title: "Delivery Charge",
          amount: "2800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "HEAVY",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.7 kms",
        hasSurge: false,
        sla: {
          restaurantId: "91493",
          deliveryTime: 52,
          minDeliveryTime: 52,
          maxDeliveryTime: 52,
          lastMileTravel: 1.7000000476837158,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "HEAVY",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.0",
        totalRatings: 5000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "91481",
        name: "Gwalia Sweets & Fast Food",
        uuid: "b603206e-066b-4d7f-a511-e3d889cc9043",
        city: "10",
        area: "Bapunagar",
        totalRatingsString: "5000+ ratings",
        cloudinaryImageId: "guqjxmcaylwpr89cgiaw",
        cuisines: [
          "Sweets",
          "North Indian",
          "Chaat",
          "Snacks",
          "Bakery",
          "Desserts",
          "Beverages",
        ],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 53,
        minDeliveryTime: 53,
        maxDeliveryTime: 53,
        slaString: "53 MINS",
        lastMileTravel: 1.7000000476837158,
        slugs: {
          restaurant: "gwalia-sweets-bapunagar-bapunagar",
          city: "ahmedabad",
        },
        cityState: "10",
        address:
          "White House, Opposite Shaktidhara Society, Bapunagar, Ahmedabad",
        locality: "Shaktidhara Society",
        parentId: 92340,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "20% off",
          shortDescriptionList: [
            {
              meta: "20% off | Use PARTY",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "20% off | Use code PARTY",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "20% OFF",
          shortDescriptionList: [
            {
              meta: "Use PARTY",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "20% off | Use code PARTY",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [
          {
            tradeCampaignHeaders: [],
            avgRating: "--",
            totalRatings: 0,
            area: "Nikol",
            city: "10",
            locality: "Nikol-Naroda Road",
            deliveryTime: 55,
            minDeliveryTime: 55,
            maxDeliveryTime: 55,
            slaString: "55 MINS",
            select: false,
            id: "584898",
            slugs: {
              restaurant: "gwalia-sweets-nikol-bapunagar-bapunagar",
              city: "ahmedabad",
            },
            feeDetails: {
              restaurant_id: 584898,
              fees: [
                {
                  name: "distance",
                  fee: 2800,
                  message: "",
                },
                {
                  name: "rain",
                  fee: 0,
                  message: "",
                },
                {
                  name: "time",
                  fee: 0,
                  message: "",
                },
              ],
              total_fee: 2800,
              message: "",
              title: "Delivery Charge",
              amount: "2800",
              icon: "",
            },
            promoted: false,
            adTrackingID: "",
          },
        ],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 2800,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2800,
          message: "",
          title: "Delivery Charge",
          amount: "2800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "HEAVY",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.7 kms",
        hasSurge: false,
        sla: {
          restaurantId: "91481",
          deliveryTime: 53,
          minDeliveryTime: 53,
          maxDeliveryTime: 53,
          lastMileTravel: 1.7000000476837158,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "HEAVY",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.9",
        totalRatings: 5000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "580911",
        name: "Joy Restaurant",
        uuid: "037baa50-1b03-4727-94f1-520580bdf4e0",
        city: "10",
        area: "Bapunagar",
        totalRatingsString: "100+ ratings",
        cloudinaryImageId: "jq402qp20evrhkaj1wqx",
        cuisines: ["North Indian", "Chinese", "Fast Food", "Indian", "Pizzas"],
        tags: [],
        costForTwo: 50000,
        costForTwoString: "₹500 FOR TWO",
        deliveryTime: 51,
        minDeliveryTime: 51,
        maxDeliveryTime: 51,
        slaString: "51 MINS",
        lastMileTravel: 1.899999976158142,
        slugs: {
          restaurant: "joy-restaurant-bapunagar-bapunagar",
          city: "ahmedabad",
        },
        cityState: "10",
        address:
          "GF/ 8 to 10, Shayona Arcade opp Dinesh Champers Bapunagar, Ahmedabad,Gujarat-380024",
        locality: "Shayona Arcade",
        parentId: 111601,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 2800,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2800,
          message: "",
          title: "Delivery Charge",
          amount: "2800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "HEAVY",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.8 kms",
        hasSurge: false,
        sla: {
          restaurantId: "580911",
          deliveryTime: 51,
          minDeliveryTime: 51,
          maxDeliveryTime: 51,
          lastMileTravel: 1.899999976158142,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "HEAVY",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.9",
        totalRatings: 100,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "220243",
        name: "Mama Rajwadi Ganthiya",
        uuid: "a9ca6e4c-bda1-4653-a77d-85540e0ef943",
        city: "10",
        area: "Odhav",
        totalRatingsString: "500+ ratings",
        cloudinaryImageId: "zjxsvr8olmnczzo1dykb",
        cuisines: ["Snacks", "Gujarati"],
        tags: [],
        costForTwo: 15000,
        costForTwoString: "₹150 FOR TWO",
        deliveryTime: 54,
        minDeliveryTime: 54,
        maxDeliveryTime: 54,
        slaString: "54 MINS",
        lastMileTravel: 1.899999976158142,
        slugs: {
          restaurant: "mama-rajwadi-ganthiya-bapunagar-bapunagar",
          city: "ahmedabad",
        },
        cityState: "10",
        address:
          "JAGVANDANA SHOPPING CENTER PARVATI NAGAR  VIRATNAGAR CHAR RASTA ODHAV AHMEDABAD",
        locality: "Bapunagar",
        parentId: 131104,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "15% off",
          shortDescriptionList: [
            {
              meta: "15% off | Use PARTY",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "15% off | Use code PARTY",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "15% OFF",
          shortDescriptionList: [
            {
              meta: "Use PARTY",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "15% off | Use code PARTY",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 2800,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2800,
          message: "",
          title: "Delivery Charge",
          amount: "2800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "HEAVY",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.8 kms",
        hasSurge: false,
        sla: {
          restaurantId: "220243",
          deliveryTime: 54,
          minDeliveryTime: 54,
          maxDeliveryTime: 54,
          lastMileTravel: 1.899999976158142,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "HEAVY",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.2",
        totalRatings: 500,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "592741",
        name: "MMV - Mumbaiya Misal & Vadapav",
        uuid: "e14e71f5-4699-4f12-8f8f-53816ee60b13",
        city: "10",
        area: "Bapunagar",
        totalRatingsString: "50+ ratings",
        cloudinaryImageId: "7a74905b5e257a18ce1e91d6b1367b89",
        cuisines: ["Maharashtrian", "Fast Food", "Street Food", "Beverages"],
        tags: [],
        costForTwo: 15000,
        costForTwoString: "₹150 FOR TWO",
        deliveryTime: 52,
        minDeliveryTime: 52,
        maxDeliveryTime: 52,
        slaString: "52 MINS",
        lastMileTravel: 1.7000000476837158,
        slugs: {
          restaurant: "mumbaiya-misal-and-vadapav-bapunagar-bapunagar-2",
          city: "ahmedabad",
        },
        cityState: "10",
        address:
          "17, 154, PRARTHANA COMPLEX, NR. INDICA LABORATORY, INDIA COLONY CHAR RASTA, BAPUNAGAR,- 380024",
        locality: "India Colony Char Rasta",
        parentId: 429250,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [
          {
            tradeCampaignHeaders: [],
            avgRating: "4.3",
            totalRatings: 100,
            area: "NIKOL",
            city: "10",
            locality: "Bapunagar",
            deliveryTime: 51,
            minDeliveryTime: 51,
            maxDeliveryTime: 51,
            slaString: "51 MINS",
            select: false,
            id: "529911",
            slugs: {
              restaurant: "the-three-minds-bapunagar-bapunagar",
              city: "ahmedabad",
            },
            feeDetails: {
              restaurant_id: 529911,
              fees: [
                {
                  name: "distance",
                  fee: 2800,
                  message: "",
                },
                {
                  name: "rain",
                  fee: 0,
                  message: "",
                },
                {
                  name: "time",
                  fee: 0,
                  message: "",
                },
              ],
              total_fee: 2800,
              message: "",
              title: "Delivery Charge",
              amount: "2800",
              icon: "",
            },
            promoted: false,
            adTrackingID: "",
          },
          {
            tradeCampaignHeaders: [],
            avgRating: "4.2",
            totalRatings: 50,
            area: "Vastrapur",
            city: "10",
            locality: "Nr Drive In Cinema",
            deliveryTime: 51,
            minDeliveryTime: 51,
            maxDeliveryTime: 51,
            slaString: "51 MINS",
            select: false,
            id: "588545",
            slugs: {
              restaurant: "mumbaiya-misal-and-vadapav-vastrapur-vastrapur",
              city: "ahmedabad",
            },
            feeDetails: {
              restaurant_id: 588545,
              fees: [
                {
                  name: "distance",
                  fee: 10100,
                  message: "",
                },
                {
                  name: "time",
                  fee: 0,
                  message: "",
                },
                {
                  name: "special",
                  fee: 0,
                  message: "",
                },
              ],
              total_fee: 10100,
              message: "",
              title: "Delivery Charge",
              amount: "10100",
              icon: "",
            },
            promoted: false,
            adTrackingID: "",
          },
          {
            tradeCampaignHeaders: [],
            avgRating: "4.0",
            totalRatings: 100,
            area: "Thaltej",
            city: "10",
            locality: "Ghatlodia",
            deliveryTime: 48,
            minDeliveryTime: 48,
            maxDeliveryTime: 48,
            slaString: "48 MINS",
            select: false,
            id: "531420",
            slugs: {
              restaurant: "mumbaiya-misal-and-vadapav-ghatlodia-ghatlodia-2",
              city: "ahmedabad",
            },
            feeDetails: {
              restaurant_id: 531420,
              fees: [
                {
                  name: "distance",
                  fee: 11700,
                  message: "",
                },
                {
                  name: "time",
                  fee: 0,
                  message: "",
                },
                {
                  name: "special",
                  fee: 0,
                  message: "",
                },
              ],
              total_fee: 11700,
              message: "",
              title: "Delivery Charge",
              amount: "11700",
              icon: "",
            },
            promoted: false,
            adTrackingID: "",
          },
        ],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 2800,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2800,
          message: "",
          title: "Delivery Charge",
          amount: "2800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "HEAVY",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.7 kms",
        hasSurge: false,
        sla: {
          restaurantId: "592741",
          deliveryTime: 52,
          minDeliveryTime: 52,
          maxDeliveryTime: 52,
          lastMileTravel: 1.7000000476837158,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "HEAVY",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.1",
        totalRatings: 50,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "412665",
        name: "Subway",
        uuid: "456fe48f-94d9-4c2e-8db9-b2378a6e4385",
        city: "10",
        area: "Nikol",
        totalRatingsString: "500+ ratings",
        cloudinaryImageId: "1ace5fa65eff3e1223feb696c956b38b",
        cuisines: ["Salads", "Healthy Food"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 43,
        minDeliveryTime: 43,
        maxDeliveryTime: 43,
        slaString: "43 MINS",
        lastMileTravel: 2.799999952316284,
        slugs: {
          restaurant: "subway-nikol-bapunagar-bapunagar",
          city: "ahmedabad",
        },
        cityState: "10",
        address:
          "Shop no.05 & 06 opp.Platinium mall PlazaShukan bunglow charrasta, Nikol,Ahmedabad, Gujarat382350, India",
        locality: "Oppplatinium Mall",
        parentId: 2,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 2800,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2800,
          message: "",
          title: "Delivery Charge",
          amount: "2800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "HEAVY",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2.7 kms",
        hasSurge: false,
        sla: {
          restaurantId: "412665",
          deliveryTime: 43,
          minDeliveryTime: 43,
          maxDeliveryTime: 43,
          lastMileTravel: 2.799999952316284,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "HEAVY",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.2",
        totalRatings: 500,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "546026",
        name: "Cake Di Bakery & More",
        uuid: "a21bb7b2-ba92-4ba1-9945-a7069baddc2e",
        city: "10",
        area: "Bapunagar",
        totalRatingsString: "Too Few Ratings",
        cloudinaryImageId: "r5njmug1vqxg6gz3zoff",
        cuisines: ["Indian"],
        tags: [],
        costForTwo: 5000,
        costForTwoString: "₹50 FOR TWO",
        deliveryTime: 53,
        minDeliveryTime: 53,
        maxDeliveryTime: 53,
        slaString: "53 MINS",
        lastMileTravel: 2.0999999046325684,
        slugs: {
          restaurant: "cake-di-bakery-&-more-bapunagar-bapunagar",
          city: "ahmedabad",
        },
        cityState: "10",
        address:
          "13/2 New arvind nagar society opp.  KALUPUR COMMERCIAL BANK, , Bapunagar, Ahmedabad, Gujarat 380024, India",
        locality: "New Arvind Nagar",
        parentId: 328053,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 2800,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2800,
          message: "",
          title: "Delivery Charge",
          amount: "2800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "HEAVY",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2 kms",
        hasSurge: false,
        sla: {
          restaurantId: "546026",
          deliveryTime: 53,
          minDeliveryTime: 53,
          maxDeliveryTime: 53,
          lastMileTravel: 2.0999999046325684,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "HEAVY",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "--",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "667605",
        name: "Italio's Pizza\t",
        uuid: "1101b5bd-0b26-49e5-8a77-7570212af569",
        city: "10",
        area: "Bapunagar",
        totalRatingsString: "Too Few Ratings",
        cloudinaryImageId: "906c0affa7d8ff78a3e4db88b4433cde",
        cuisines: ["Indian"],
        tags: [],
        costForTwo: 50000,
        costForTwoString: "₹500 FOR TWO",
        deliveryTime: 59,
        minDeliveryTime: 59,
        maxDeliveryTime: 59,
        slaString: "59 MINS",
        lastMileTravel: 1.600000023841858,
        slugs: {
          restaurant: "italio's-pizza-bapunagar-bapunagar",
          city: "ahmedabad",
        },
        cityState: "10",
        address:
          "PLOT-124 DANEV PARK SOCIETY , OPP  MUKTIDHAM ESTATE, NICOL GAM ROAD.  NARODA AHMEDABAD, Naroda(North  Zone), Ahmedabad Municipal Corporation,  Ahmedabad, Gujarat - 380038",
        locality: "Nicol Gam Road",
        parentId: 288071,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 2800,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2800,
          message: "",
          title: "Delivery Charge",
          amount: "2800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "HEAVY",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.6 kms",
        hasSurge: false,
        sla: {
          restaurantId: "667605",
          deliveryTime: 59,
          minDeliveryTime: 59,
          maxDeliveryTime: 59,
          lastMileTravel: 1.600000023841858,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "HEAVY",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "--",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "158791",
        name: "Karnavati Dabeli And Vadapav",
        uuid: "9854be29-67bd-459f-94e9-e1934e46e42a",
        city: "10",
        area: "NavaNaroda",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "wu2qcuummulej4orwsvd",
        cuisines: ["Snacks"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 46,
        minDeliveryTime: 46,
        maxDeliveryTime: 46,
        slaString: "46 MINS",
        lastMileTravel: 1.600000023841858,
        slugs: {
          restaurant: "karnavati-dabeli-and-vadapav-nikol-bapunagar",
          city: "ahmedabad",
        },
        cityState: "10",
        address: "A/23 Nilam Bungalows Krishnanagar Road Ahmedabad",
        locality: "Nikol",
        parentId: 115238,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "FLAT150 off",
          shortDescriptionList: [
            {
              meta: "FLAT150 off | Use FLATDEAL",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FLAT150 off | Use FLATDEAL",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "₹150 OFF",
          shortDescriptionList: [
            {
              meta: "Use FLATDEAL",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FLAT150 off | Use FLATDEAL",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 2800,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2800,
          message: "",
          title: "Delivery Charge",
          amount: "2800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "HEAVY",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.6 kms",
        hasSurge: false,
        sla: {
          restaurantId: "158791",
          deliveryTime: 46,
          minDeliveryTime: 46,
          maxDeliveryTime: 46,
          lastMileTravel: 1.600000023841858,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "HEAVY",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.6",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
];



const App = ()=>{
    return(
        <div>
            <Header/>
            <Body/>
            <Footer/>
        </div>
    )
}
const root = ReactDOM.createRoot(document.querySelector('#root'))
root.render(<App/>)